config/routes.rb
Rails.application.routes.draw do
  default_url_options Rails.application.config.action_mailer.default_url_options

  # Serve websocket cable requests in-process
  mount ActionCable.server => '/cable'

  resources :posts, only: [:index, :new, :create]
  devise_for :users, :controllers => { registrations: 'registrations' }

  resources :users, only: [:update] do
    collection do
      get "search"
    end
  end

  get '/user/:username' => 'users#show', as: :user_profile, constraints: { username: /[^\/]+/ }
  get "/user/:username/follow" => 'users#follow', as: :follow_user, constraints: { username: /[^\/]+/ }
  get "/user/:username/unfollow" => 'users#unfollow', as: :unfollow_user, constraints: { username: /[^\/]+/ }

  root 'home#index'
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable,
         :validatable, :confirmable
  # An user has many posts
  has_many :posts, dependent: :destroy
  # Mapping the relationships for Followers and Followeds
  has_many :followings
  has_many :followerships, class_name: 'Following', foreign_key: 'user_id'
  has_many :followedships, class_name: 'Following', foreign_key: 'follower_id'
  has_many :followers, through: :followerships, source: :follower
  has_many :followeds, through: :followedships, source: :user
  # The user avatar property is a Carrierwave Uploader wich supports only images
  mount_uploader :avatar, AvatarUploader
  # Virtual attribute for authenticating by either username or email
  # This is in addition to a real persisted field like 'username'
  attr_accessor :login

  validates :name, presence: true, length: { in: 3..255 }
  # The username is case insensitive, i.e., Caiofct is the same as caiofct
  validates :username, presence: true, uniqueness: {
    :case_sensitive => false
  }, length: { in: 3..255 }

  # Only allow letter, number, underscore and punctuation for the username.
  # Avoid the problem with a username with an email format
  validates_format_of :username, with: /^[a-zA-Z0-9_\.]*$/, multiline: true

  # Finds an specific user by username
  scope :by_username, lambda { |username| where("username" => username) }
  # Finds all confirmed users
  scope :confirmed, lambda { where("confirmed_at IS NOT NULL") }

  # To determine whether a user can follow another, we have some pre-requisites:
  # 1. The user to be followed can`t be the same user that wants to follow him (An user cannot follow himself)
  # 2. The user to be followed can`t be followed yet by the user (You cannot have duplicates between a follower and followed pair)
  def can_follow?(user)
    self.id != user.id && !following?(user)
  end

  # Verifying whether a user is following another one
  def following?(user)
    !Following.find_by_follower_id_and_user_id(self.id, user.id).blank?
  end

  # Adds the user in parameter to the list of followeds of the instance user
  def follow(user)
    if can_follow?(user)
      self.followeds << user
      return true
    end
    false
  end

  # Removes the user in the parameter from the Followings table where the
  # instance user is in the follower_id and the parameter user is in the user_id
  def unfollow(user)
    followed = Following.find_by_follower_id_and_user_id(self.id, user.id)
    if !followed.blank?
      followed.destroy
    end
  end

  # Overrinding the devise's logic to lookup a user in the database to use
  # the username or email
  def self.find_for_database_authentication(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions.to_hash).where(["lower(username) = :value OR lower(email) = :value", { :value => login.downcase }]).first
    elsif conditions.has_key?(:username) || conditions.has_key?(:email)
      conditions[:email].dup.downcase! if conditions[:email]
      conditions[:username].dup.downcase! if conditions[:username]
      where(conditions.to_hash).first
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :authenticate_user!, only: [:show, :search]
  before_action :set_user, only: [:show, :follow, :unfollow]

  # GET /users/show/:username
  def show
    @posts = Post.by_user_id(@user.id).order("created_at DESC")
  end

  # PUT /users
  # PUT /users.json
  def update
    @user = User.find params[:id]
    if @user.update(user_params)
      redirect_to user_profile_path(@user.username)
    else
      redirect_to user_profile_path(@user.username), notice: "Não foi possível fazer upload da imagem. Por favor, tente novamente."
    end
  end

  # GET /user/:username/follow
  def follow
    if current_user.follow(@user)
      UserMailer.followed_by_user(@user, current_user).deliver
    end

    redirect_to user_profile_path(@user.username)
  end

  # GET /user/:username/unfollow
  def unfollow
    current_user.unfollow(@user)
    redirect_to user_profile_path(@user.username)
  end

  # GET /users/search
  def search
    @users = []
    if !params[:q].blank?
      if params[:q].strip == ":all"
        @users = User.confirmed
      else
        search_term = "%#{params[:q].strip.gsub(' ','%')}%"
        @users = User.confirmed.where('name ilike ? OR username ilike ?', search_term, search_term)
      end
    end
  end

  private

  # Avoiding repetitions and set`s a user before many actions
  def set_user
    @user = User.confirmed.by_username(params[:username]).first
    if @user.blank?
      render file: "public/404.html", status: 404
      return
    end
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def user_params
    params.require(:user).permit(:name, :avatar)
  end
end

app/views/users/_user.html.erb
<div class="col-md-3 user-grid-item">
  <div class="row m-t">
    <div class="col-md-5">
      <%= profile_image(:small, {}, user) %>
    </div>
    <div class="col-md-7 text-right">
      <% if !current_user.blank? && current_user.can_follow?(user) %>
        <%= link_to follow_user_path(user.username), class: "follow-btn btn btn-default", style: "color: #676a6c;", disable_with: t('users.disable_following') do %>
          <i class="fa fa-user-plus"></i>
          <%=t('users.follow')%>
        <% end %>
      <% elsif !current_user.blank? && current_user.following?(user) %>
        <%= link_to unfollow_user_path(user.username), class: "unfollow-btn btn btn-success", disable_with: t('users.disable_following') do %>
          <i class="fa fa-user-times"></i>
          <%=t('users.unfollow')%>
        <% end %>
      <% end %>
    </div>
  </div>
  <div class="col-md-12 m-b" style="padding-left: 0 !important;">
    <h2 id="profile-name" class="font-bold no-margins"><%=user.name%></h2>
    <small id="profile-username">@<%=user.username%></small>
  </div>
</div>

app/views/users/search.html.erb
<div class="users-grid row">
  <% @users.each do |user| %>
    <%= render user %>
  <% end %>
</div>

app/views/users/show.html.erb
<div class="row">
  <div class="col-lg-3 m-b">
    <div class="widget-head-color-box navy-bg p-lg text-center">
      <%= profile_image(:default, {}, @user, true) %>
      <%= simple_form_for(@user, html: { multipart: true, style: "height: 0px;" }) do |f| %>
        <%= f.input :avatar, as: :file, wrapper_html: { style: "visibility: hidden;" } %>
        <%= f.submit t('users.update_avatar'), id: "send_avatar_btn", style: "visibility: hidden;" %>
      <% end %>
      <div class="m-b-xs">
        <h2 id="profile-name" class="font-bold no-margins"><%=@user.name%></h2>
        <small id="profile-username">@<%=@user.username%></small>
      </div>
      <div class="m-b-xs">
        <i class="fa fa-calendar"></i>&nbsp;&nbsp;
        <%=t('users.joined_at', date: l(@user.created_at, format: :default))%> <%=  %>
      </div>
      <% if !current_user.blank? && current_user.can_follow?(@user) %>
        <div class="row">
          <%= link_to follow_user_path(@user.username), class: "btn btn-default", style: "color: #676a6c;", disable_with: t('users.disable_following') do %>
            <i class="fa fa-user-plus"></i>
            <%=t('users.follow')%>
          <% end %>
        </div>
      <% elsif !current_user.blank? && current_user.following?(@user) %>
        <div class="row">
          <%= link_to unfollow_user_path(@user.username), class: "btn btn-success", disable_with: t('users.disable_following') do %>
            <i class="fa fa-user-times"></i>
            <%=t('users.unfollow')%>
          <% end %>
        </div>
      <% end %>
      <div class="row m-t-xs">
        <div class="col-xs-4"><%=t('posts.post_count')%></div>
        <div class="col-xs-4"><%=t('posts.following_count')%></div>
        <div class="col-xs-4"><%=t('posts.followers_count')%></div>
      </div>
      <div class="row">
        <div class="col-xs-4"><%= @user.posts.length %></div>
        <div class="col-xs-4"><%= @user.followeds.length %></div>
        <div class="col-xs-4"><%= @user.followers.length %></div>
      </div>
    </div>
  </div>
  <div class="col-lg-9">
    <div class="ibox float-e-margins">
      <div class="ibox-content">
        <div class="chat-activity-list posts">
          <% if @posts.blank? %>
            <div class="text-center empty">
              <h1>
                <%=t('users.empty_for_user', username: @user.name)%>
              </h1>
            </div>
          <% else %>
            <% @posts.each do |post| %>
              <%= render post %>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>