config/routes.rb
Rails.application.routes.draw do
  default_url_options Rails.application.config.action_mailer.default_url_options

  # Serve websocket cable requests in-process
  mount ActionCable.server => '/cable'

  resources :posts, only: [:index, :new, :create]
  devise_for :users, :controllers => { registrations: 'registrations' }

  resources :users, only: [:update] do
    collection do
      get "search"
    end
  end

  get '/user/:username' => 'users#show', as: :user_profile, constraints: { username: /[^\/]+/ }
  get "/user/:username/follow" => 'users#follow', as: :follow_user, constraints: { username: /[^\/]+/ }
  get "/user/:username/unfollow" => 'users#unfollow', as: :unfollow_user, constraints: { username: /[^\/]+/ }

  root 'home#index'
end

app/views/layouts/_menu.html.erb
<div class="row border-bottom white-bg">
  <nav class="navbar navbar-fixed-top global-nav" role="navigation">
      <div class="navbar-header">
          <button aria-controls="navbar" aria-expanded="false" data-target="#navbar" data-toggle="collapse" class="navbar-toggle collapsed" type="button">
              <i class="fa fa-reorder"></i>
          </button>
          <a href="#" class="navbar-brand">Awesome Rails Microblog</a>
      </div>
      <div class="navbar-collapse collapse" id="navbar">
          <ul class="nav navbar-nav">
            <%= render partial: "layouts/menu_items" %>
          </ul>
          <ul class="nav navbar-top-links navbar-right">
            <form action="/users/search" method="GET" class="navbar-form navbar-left">
              <div class="form-group" style="width: 250px;">
                <input id="search-box" class="form-control search-input" name="q" type="text" placeholder="<%=t('menu.search_placeholder')%>" value="<%=params[:q]%>"></input>
                <input type="submit" style="visibility: hidden; height: 0; width: 0; position: absolute;" value="Buscar">
              </div>
            </form>
            <% if !current_user.blank? %>
              <li class="dropdown">
                <a style="padding-right: 0;" class="dropdown-toggle count-info" href="#" data-toggle="dropdown" aria-expanded="false">
                  <%= profile_image :very_small, { "margin-top": "-3px" } %>
                  <div class="caret" style="float: right; margin-top: 8px; margin-left: 5px;"></div>
                  <div style="float: right; padding-left: 10px; margin-top: -1px;"><%= current_user.name %></div>
                </a>
                <ul class="dropdown-menu dropdown-alerts">
                  <li>
                    <%= link_to user_profile_path(current_user.username) do %>
                      <div>
                        <div><%=t('menu.see_profile')%></div>
                        <div style="font-size: 12px; margin-top: -8px; color: rgb(136, 153, 166);">@<%=current_user.username%></div>
                      </div>
                    <% end %>
                  </li>
                  <li>
                    <%= link_to t('login.signout'), destroy_user_session_path, method: :delete, id: "sign_out_link" %>
                  </li>
                </ul>
              </li>
            <% else %>
              <li>
                <%= link_to t('login.signin'), new_user_session_path %>
              </li>
            <% end %>
          </ul>
      </div>
  </nav>
</div>

app/views/layouts/_menu_items.html.erb
<li class="<%= 'active' if params[:controller] == 'home' || params[:controller] == 'posts' %>">
  <% if current_user %>
    <%= link_to posts_path do %>
      <span class="nav-label"><%= t("menu.home")%></span>
    <% end %>
  <% else %>
    <%= link_to root_path do %>
      <span class="nav-label"><%= t("menu.home")%></span>
    <% end %>
  <% end %>
</li>

app/views/layouts/_messages.html.erb
<% flash.each do |type, message| %>
  <% if !message.blank? && message.is_a?(String) %>
    <div class="alert <%=bootstrap_class_for(type)%> alert-dismissable alert-modal" style="visibility: hidden;">
      <button class="close" type="button" data-dismiss="alert" aria-hidden="true">×</button>
      <%= sanitize message %>
    </div>
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>
    Awesome Rails Microblog
  </title>
  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">
  <meta name="turbolinks-cache-control" content="no-cache">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  <%= csrf_meta_tags %>
  <%= action_cable_meta_tag %>
</head>
  <body class="top-navigation">
    <div id="wrapper">
      <div id="page-wrapper" class="gray-bg">
        <%= render "layouts/menu" %>
        <div class= "wrapper wrapper-content">
            <%= render 'toastr_rails/flash' %>
            <%= render 'layouts/messages' %>
            <%= yield %>
        </div>
      </div>
    </div>
  </body>
</html>